name: CI

on:
    push:

jobs:
    lint:
        name: 'Lint code'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm run build

            - name: Check lint
              run: pnpm run lint

            - name: TypeScript check
              run: pnpm run check

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        needs: lint
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm run build

            - name: Publish to npm
              run: pnpm publish --provenance --access public --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
